# Generated by Django 2.0.7 on 2020-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=30)),
                ('customerEmail', models.CharField(max_length=30)),
                ('customerPassword', models.CharField(max_length=30)),
                ('customerContact', models.CharField(max_length=30)),
                ('customerAddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
