# Generated by Django 2.0.7 on 2020-12-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_admin_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
