# Generated by Django 2.0.7 on 2020-12-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20201230_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('custemail', models.CharField(max_length=30)),
                ('totalbill', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
