# Generated by Django 3.0.5 on 2021-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.IntegerField()),
                ('ordId', models.IntegerField()),
                ('foodQuant', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'orderSummary',
            },
        ),
    ]
